create extension if not exists pgcrypto;

create table if not exists public.summary_groups (
  id text primary key,
  name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.line_groups (
  line_group_id text primary key,
  line_group_name text not null,
  summary_group_id text not null references public.summary_groups(id),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.category_aliases (
  alias text primary key,
  canonical_category text not null check (canonical_category in ('A','B','E','F','G')),
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.allocation_rules (
  summary_group_id text not null references public.summary_groups(id),
  category text not null check (category in ('A','B','E','F','G')),
  threshold integer not null check (threshold > 0),
  destination text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (summary_group_id, category)
);

create table if not exists public.webhook_events (
  webhook_event_id text primary key,
  destination text not null,
  event_type text not null,
  line_group_id text,
  user_id text,
  is_redelivery boolean not null default false,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  destination text not null,
  webhook_event_id text not null unique references public.webhook_events(webhook_event_id),
  message_id text,
  business_date date not null,
  event_timestamp timestamptz not null,
  line_group_id text not null,
  summary_group_id text references public.summary_groups(id),
  user_id text,
  message_type text not null,
  raw_text text,
  normalized_text text,
  parse_status text not null default 'PENDING' check (parse_status in ('PENDING','PARSED','PARTIAL','REVIEW','IGNORE','UNSEND')),
  parser_version text,
  unsent boolean not null default false,
  unsent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (destination, message_id)
);

create index if not exists messages_business_group_idx
  on public.messages (business_date, summary_group_id, line_group_id);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  message_record_id uuid not null references public.messages(id) on delete cascade,
  business_date date not null,
  line_group_id text not null,
  summary_group_id text not null references public.summary_groups(id),
  category text not null check (category in ('A','B','E','F','G')),
  code text not null,
  quantity integer not null check (quantity > 0),
  unsent_flag boolean not null default false,
  parser_version text not null,
  created_at timestamptz not null default now(),
  unique (message_record_id, category, code)
);

create index if not exists order_items_summary_idx
  on public.order_items (business_date, summary_group_id, category, code);

create table if not exists public.review_items (
  id bigint generated by default as identity primary key,
  message_record_id uuid not null unique references public.messages(id) on delete cascade,
  reason_codes jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  status text not null default 'OPEN' check (status in ('OPEN','RESOLVED','IGNORED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.unsend_events (
  id uuid primary key default gen_random_uuid(),
  webhook_event_id text not null unique references public.webhook_events(webhook_event_id),
  destination text not null,
  message_id text not null,
  line_group_id text,
  user_id text,
  matched_message_record_id uuid references public.messages(id),
  derived_qty_total integer not null default 0,
  unsent_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.allocation_confirmations (
  business_date date not null,
  summary_group_id text not null references public.summary_groups(id),
  category text not null check (category in ('A','B','E','F','G')),
  code text not null,
  confirmed_transfer integer not null default 0 check (confirmed_transfer >= 0),
  confirmed_at timestamptz,
  confirmed_by text,
  primary key (business_date, summary_group_id, category, code)
);

create or replace view public.current_summary as
select
  oi.business_date,
  oi.summary_group_id,
  oi.category,
  oi.code,
  sum(oi.quantity)::bigint as order_total,
  sum(case when oi.unsent_flag then oi.quantity else 0 end)::bigint as unsent_qty,
  sum(case when oi.unsent_flag then 0 else oi.quantity end)::bigint as active_equivalent,
  max(oi.created_at) as last_updated
from public.order_items oi
group by oi.business_date, oi.summary_group_id, oi.category, oi.code;

create or replace view public.allocation_state as
select
  cs.business_date,
  cs.summary_group_id,
  cs.category,
  cs.code,
  cs.order_total,
  ar.threshold,
  ar.destination,
  greatest(0, ((cs.order_total::bigint / ar.threshold::bigint) - 1) * ar.threshold::bigint) as should_transfer,
  coalesce(ac.confirmed_transfer, 0)::bigint as confirmed_transfer,
  greatest(
    0,
    greatest(0, ((cs.order_total::bigint / ar.threshold::bigint) - 1) * ar.threshold::bigint)
      - coalesce(ac.confirmed_transfer, 0)::bigint
  ) as transfer_now,
  case
    when coalesce(ac.confirmed_transfer, 0)::bigint > greatest(0, ((cs.order_total::bigint / ar.threshold::bigint) - 1) * ar.threshold::bigint)
      then 'REVIEW'
    when greatest(
      0,
      greatest(0, ((cs.order_total::bigint / ar.threshold::bigint) - 1) * ar.threshold::bigint)
        - coalesce(ac.confirmed_transfer, 0)::bigint
    ) > 0 then 'TRANSFER_REQUIRED'
    else 'OK'
  end as status
from public.current_summary cs
join public.allocation_rules ar
  on ar.summary_group_id = cs.summary_group_id
 and ar.category = cs.category
 and ar.enabled = true
left join public.allocation_confirmations ac
  on ac.business_date = cs.business_date
 and ac.summary_group_id = cs.summary_group_id
 and ac.category = cs.category
 and ac.code = cs.code;

-- Internal MVP tables: enable RLS and expose no anon/authenticated policy yet.
alter table public.summary_groups enable row level security;
alter table public.line_groups enable row level security;
alter table public.category_aliases enable row level security;
alter table public.allocation_rules enable row level security;
alter table public.webhook_events enable row level security;
alter table public.messages enable row level security;
alter table public.order_items enable row level security;
alter table public.review_items enable row level security;
alter table public.unsend_events enable row level security;
alter table public.allocation_confirmations enable row level security;

revoke all on public.summary_groups from anon, authenticated;
revoke all on public.line_groups from anon, authenticated;
revoke all on public.category_aliases from anon, authenticated;
revoke all on public.allocation_rules from anon, authenticated;
revoke all on public.webhook_events from anon, authenticated;
revoke all on public.messages from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.review_items from anon, authenticated;
revoke all on public.unsend_events from anon, authenticated;
revoke all on public.allocation_confirmations from anon, authenticated;
revoke all on public.current_summary from anon, authenticated;
revoke all on public.allocation_state from anon, authenticated;

-- Seed only safe parser config. Replace/add real groups and allocation rules later.
insert into public.summary_groups (id, name)
values ('NORTH', 'ภาคเหนือ'), ('SOUTH', 'ภาคใต้')
on conflict (id) do nothing;

insert into public.category_aliases (alias, canonical_category)
values
  ('A','A'), ('a','A'), ('น','A'),
  ('B','B'), ('b','B'),
  ('E','E'), ('F','F'), ('G','G')
on conflict (alias) do nothing;
